ALTER TABLE users
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE categories
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE financial_accounts
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;